# Generated by Django 3.1.1 on 2020-11-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('jobs', models.CharField(max_length=100, null=True)),
                ('job_description', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
